# Preliminary notes

## Basic set notation

A set $S$ is an unordered collection of its elements, e.g., $$S = \{ 1, 2, 3 \}.$$ When $x$ is an element, we write $x\in S$. Here, $1 \in S$ but $0 \notin S$. There is no limit to the number of elements a set can have. In particular $\emptyset = \{ \}$ denotes the empty set. An infinite set is the set of natural numbers.

When all elements of one set $S$ are also elements of another set $T$, we write $S \subset T$.

From two sets $S$ and $T$ we can construct new sets: The union $S \cup T$ consists of all elements of either set. The intersection $S \cap T$ consists of the elements common to both sets. The set difference $S \setminus T$ consists of $S$ with the elements of $T$ taken away.

We can also specify sets using a *condition* on a set $S$, i.e., a rule $P(x)$ for every $x\in S$ that evaluates to true or false. We then define $$T = \{ x \in S \mid P(x) \}$$ to denote the set of those $x\in S$ such that $P(x)$ is true. We can also use more complicated conditions, by either using English language, or mathematical symbols. For example, $$P = \{ \frac{1}{p} \mid p \text{ is prime} \},$$ $$C^0[0,1] = \{ f : [0,1] \to \mathbb{R} \mid f \text{ is continuous} \}$$

The *cardinality* of a set, $|S|$, is the number of elements of the set $S$. The cardinality of the natural numbers is denoted $\aleph_0$ ("aleph naught"). Two sets have the same cardinality if and only if they can be mapped one-to-one onto each other.

It is common to denote a set of sets a *family of sets*. Mathematically, there is (almost) no difference, since all mathematical objects are sets, but in everyday maths usage, we usually do not consider a number as a set, for example.

We can build *cartesian products of sets*. The cartesian product $S\times T$ is the set of ordered pairs $(x,y)$, where $x\in S$ and $y \in T$. Note that an ordered pair is not the same as the set $\{x, y\}$, which is *unordered*. Similarly, cartesian products of $n$ sets is an ordered $n$-tuple. A useful example is $\mathbb{R}^3 = \mathbb{R} \times \mathbb{R} \times \mathbb{R} = \{ (x,y,z) \mid x, y, z \in \mathbb{R}\}$, that is, space.

Basic set operations include:

1.  Union: $A \cup B = \{ x \mid x \in A \text{ or } x \in B \}$

2.  Intersection: $A \cap B = \{ x \mid x \in A \text{ and } x \in B \}$

3.  $A \setminus B = \{ x \in A \mid x \notin B \} = B^\complement$

A mnemonic for remembering what is union and what is section, is that in the union, the symbol is a cup, that gathers everything from $A$ and $B$.

## Functions

A *function* or *map* $f : S \to T$ from a set $S$ (the domain) to a set $T$ (codomain) is a rule that assigns to every $x \in S$ precisely one element $f(x) \in T$. The set $\{f(x)\mid x\in S\}$ is a subset of $T$, and called the *range* of $f$.

The domain is the set of possible input, the codomain is what can possibly come out, and the range is what actually comes out.

If for every $y\in T$ there is an $x\in S$ such that $f(x)=y$, i.e., all elements of $T$ are reached, we say that $f$ is *surjective*, or *onto*. If $f(x) = f(x')$ implies that $x = x'$, then $f$ is *injective* or *one-to-one*. If $f$ is both surjective and injective, we say that $f$ is *bijective*, or *one-to-one and onto*.
